version: 2.0

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: mix local.hex --force
    - run: mix local.rebar --force
    - run: mix deps.get --only test
    - run: mix test

jobs:
  "elixir-1.8":
    <<: *shared
    docker:
      - image: circleci/elixir:1.8

  "elixir-1.9":
    <<: *shared
    docker:
      - image: circleci/elixir:1.9

  "elixir-1.10":
    <<: *shared
    docker:
      - image: circleci/elixir:1.10

workflows:
  version: 2
  build:
    jobs:
      - "elixir-1.8"
      - "elixir-1.9"
      - "elixir-1.10"
