name: CI

on: [push, pull_request]

jobs:
  format:
    name: check-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 23.1
          elixir-version: 1.11.1

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

  test:
    name: OTP ${{matrix.pair.erlang}} / Elixir ${{matrix.pair.elixir}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pair:
          - erlang: 23.1
            elixir: 1.11.1
          - erlang: "23.0"
            elixir: 1.10.4
          - erlang: 22.3
            elixir: 1.9.4
          - erlang: 21.3
            elixir: 1.8.2
          - erlang: 20.3
            elixir: 1.7.4

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
